---
# tasks file for deploy_jenkins
- block: # ======== Block for Debian ========
    - name: jenkins apt repository key install 
      apt_key: url=https://pkg.jenkins.io/debian/jenkins.io.key state=present

    - name: add repository
      apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present

    - name: install java-11
      apt: name=openjdk-11-jre-headless state=present

    - name: install jenkins
      apt: name=jenkins state=present

    - name: start jenkins
      service: name=jenkins state=started
    
    - name: enable jenkins
      service: name=jenkins enabled=yes
  when: ansible_os_family == "Debian"
- block: # ======== Block for RedHat ======== 
    - name: Get repo for jenkins
      get_url: 
        url: https://pkg.jenkins.io/redhat/jenkins.repo 
        dest: /etc/yum.repos.d/jenkins.repo 
  when: ansible_os_family == "RedHat"
 
