---

- name: Install NGINX
  hosts: all
  become: yes
  tasks:
    - name: Install NGINX 
      ansible.builtin.apt: 
        name: nginx
        state: present
    - name: Enable service NGINX
      ansible.builtin.service:
        name: nginx
        enabled: yes

